theme: jekyll-theme-minimal
title: Salle de Cons
description: A salon-style gathering to share knowledge and ideas, cultivate creativity, amuse each other, and engage in connerie. (Image credit: Mohamed El Damrawy) 
logo: /assets/img/logo.png
show_downloads: false
